// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msaejzimbosfdbiejyfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYWVqemltYm9zZmRiaWVqeWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTEwNzAsImV4cCI6MjA1NzU4NzA3MH0.dlX9Td1bay4EFN2Hv6LS2NrNgOrrMIDWh74FW2TcUh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);